AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  budget-app

  Sample SAM Template for budget-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: budget-app-project

  CSVConverterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: csv_converter/
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TransactionTable
        - DynamoDBCrudPolicy:
            TableName: ChecksumsTable
      Events:
        MyS3Event:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*

  TransactionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TransactionTable
      AttributeDefinitions:
        - AttributeName: hash
          AttributeType: S
      KeySchema:
        - AttributeName: hash
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ChecksumsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ChecksumsTable
      AttributeDefinitions:
        - AttributeName: checksum
          AttributeType: S
      KeySchema:
        - AttributeName: checksum
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2